---
language:
    - python
python:
    - '2.7'
env:
    global:
        - GIT_COMMITER_NAME=ksk-uchi
        - GIT_COMMITER_EMAIL=keisuke.uchimura@gengo.com
        - GIT_AUTHOR_NAME=ksk-uchi
        - GIT_AUTHOR_EMAIL=keisuke.uchimura@gengo.com
before_script:
    - cat ~/.ssh/id_rsa
    - secret=`openssl rsautl -decrypt -inkey ~/.ssh/id_rsa -in secret`
    - pwd
    - ls -ltra
    - git branch
script:
    - git checkout gh-pages
    - date > hoge.txt
after_success:
    - git add .
    - git commit -m "UPDATE DOCUMENTATION BY TRAVIS"
    - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ $secret ] && git push -f --quiet https://${secret}@github.com/ksk-uchi/ghp_test.git gh-pages'
