---
language:
    - python
python:
    - '2.7'
install:
    - pip install -r requirements.txt --use-mirrors
env:
    global:
        - GIT_COMMITER_NAME=Travis
        - GIT_COMMITER_EMAIL=travis@travis-ci.org
        - GIT_AUTHOR_NAME=Travis
        - GIT_AUTHOR_EMAIL=travis@travis-ci.org
before_script:
    - secret=`openssl rsautl -decrypt -inkey ~/.ssh/id_rsa -in secret`
    - openssl aes-256-cbc -k "$secret" -in config.xml.enc -d -a -out config.xml
    - pwd
    - ls -ltra
    - git branch
script:
    - make multilingual-html
    - mv build ../
    - git stash
    - git checkout gh-pages
    - rm -rf build
    - mv ../build ./
    - touch .nojekyll
after_success:
    - git add .
    - git commit -m "UPDATE DOCUMENTATION BY TRAVIS"
    - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ $GH_TOKEN ] && git push -f --quiet https://${secret}@github.com/ksk-uchi/ghp_test.git gh-pages'
