---
language:
    - python
python:
    - '2.7'
install:
    - pip install -r requirements.txt --use-mirrors
env:
    global:
        - GIT_COMMITER_NAME=ksk-uchi
        - GIT_COMMITER_EMAIL=keisuke.uchimura@gengo.com
        - GIT_AUTHOR_NAME=ksk-uchi
        - GIT_AUTHOR_EMAIL=keisuke.uchimura@gengo.com
        - secure: Lhezns6VzoiujWmF4r7FIorjlZiFaKfR2qkncW32Ws1RuxFmSj2c2x/0LnjS/1gXXY29fyrQm3kPo48fd0DlfFBuguUOFPbfR9iEzba/mcbUCt7vQjF+BFYAyta3S8zzNdFclOVui1v0WlRueDwFrgfqcgWFDmvb/Az7SuHZtzQ=
before_script:
    - git clone --quiet https://github.com/ksk-uchi/ghp_test.git ghp_test
    - cd ghp_test
    - git checkout -b gh-pages
script:
    - ls -ltra
    - make multilingual-html
after_success:
    - ls -ltra
    - git add build
    - git commit -m 'Update'
    - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ $GH_TOKEN ] && git push -f --quiet https://$GH_TOKEN@github.com/ksk-uchi/ghp_test.git gh-pages'
