---
language:
    - python
python:
    - '2.7'
install:
    - pip install -r requirements.txt --use-mirrors
env:
    global:
        - GIT_COMMITER_NAME=Travis
        - GIT_COMMITER_EMAIL=travis@travis-ci.org
        - GIT_AUTHOR_NAME=Travis
        - GIT_AUTHOR_EMAIL=travis@travis-ci.org
#         - secure: Lhezns6VzoiujWmF4r7FIorjlZiFaKfR2qkncW32Ws1RuxFmSj2c2x/0LnjS/1gXXY29fyrQm3kPo48fd0DlfFBuguUOFPbfR9iEzba/mcbUCt7vQjF+BFYAyta3S8zzNdFclOVui1v0WlRueDwFrgfqcgWFDmvb/Az7SuHZtzQ=
before_script:
    - ls -ltra
#     - git clone --quiet https://github.com/ksk-uchi/ghp_test.git ghp_test
#     - git branch
#     - cd ghp_test
# script:
#     - make multilingual-html
#     - mv build ../
#     - git stash
#     - git checkout gh-pages
#     - rm -rf build
#     - mv ../build ./
#     - touch .nojekyll
# after_success:
#     - git add .
#     - git commit -m "UPDATE DOCUMENTATION BY TRAVIS"
#     - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ $GH_TOKEN ] && git push -f --quiet https://$GH_TOKEN@github.com/ksk-uchi/ghp_test.git gh-pages'
